server:
    port: 9090
    ssl:
        enabled: true
        key-store:  classpath:tomcat-ssl.keystore
        key-store-password: tomcat7
    context-path: yacramanager
    servlet-path: yacramanager

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://localhost:5432/yacra
        databaseName: yacra
        serverName: localhost
        username: yacra
        password: yacra

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    mail:
        baseUrl: http://localhost:8080
        
    security:
        bcrypt.encoder.strength: 11
        rememberme.token.validity: 1209600
        customSessionExpiredErrorCode: 901
    max.sessions: 2
    thymeleaf:
        mode: XHTML
        cache: false
    social:
        facebook:
            client:
                id: 699814763463496
                secret: b7dcd00b95fd56aef659a9f95dbeb405
        git:
            client:
                id: 2434e7df5157a95fab27
                secret: fa2e016864b1c38986906a3282e9e663cd14e835
        google:
            client:
                id: 805141202696-lhkqbmr6g7hdngk4u0hcn8cf0j0l7vp4.apps.googleusercontent.com
                secret: Tw5Qu2MUIU8MmGnFtrsjGpKP
                scope: openid profile email 
        twitter:
            client:
                id: 2434e7df5157a95fab27
                secret: fa2e016864b1c38986906a3282e9e663cd14e835
        linkedin:
            client:
                id: 77j5axnzl1vuu1
                secret: vV8FqVcgA0z6HTAt		
google:
    recaptcha:
        secretKey: 6LeHhQUTAAAAABZrel9yr-Dj_W9U_lDlrk-m01-L
        url: https://www.google.com/recaptcha/api/siteverify
metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: payme

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M
